# Topic Modeling with SciKit Learn

In this notebook we create a topic model from our corpus  using SciKit Learn's library. We'll save our results and then use another notebook to explore the results.

# Set Up

## Imports

In [103]:
import pandas as pd
import numpy as np

## Configuration

In [104]:
corpus_file = './corpora/winereviews-tapi.csv'
db_dir = './db'
data_prefix = corpus_file.split('/')[-1].split('-')[0]
csv_sep = '|'

In [105]:
data_prefix

'winereviews'

## Parameters

In [106]:
n_terms = 4000 # Vocabulary size
ngram_range = (1,4)
use_tfidf = True
n_topics = 20 # Number of topics
max_iter = 5 # Number of iterations for topic model

In [107]:
topic_cols = [t for t in range(n_topics)]

# Import Corpus Data

We import a corpus in our standard format

In [108]:
corpus = pd.read_csv(corpus_file, sep=csv_sep)
corpus.index.name = 'doc_id'

## Inspect contents

In [109]:
corpus.head()

,doc_key,doc_title,doc_label,doc_province,doc_points,doc_price,doc_content,doc_original,doc_variety,doc_taster,doc_place
doc_id,,,,,,,,,,,
0,86023,Lange 2011 Three Hills Cuvée Pinot Noir (Willa...,US,Oregon,88,40.0,"A tart, astringent Pinot, it needs a bit more ...","A tart, astringent Pinot, it needs a bit more ...",Pinot Noir,Paul Gregutt,US Oregon Willamette Valley Willamette Valley
1,45852,Finca Casa Lo Alto 2008 Reserva Red (Utiel-Req...,Spain,Levante,84,35.0,The cola and licorice aromas are candied and e...,The cola and licorice aromas are candied and e...,Red Blend,Michael Schachner,Spain Levante Utiel-Requena
2,32297,Plantagenet 2004 Omrah Cabernet Sauvignon (Wes...,Australia,Western Australia,88,15.0,"A good value, this starts off a little shaky t...","A good value, this starts off a little shaky t...",Cabernet Sauvignon,Joe Czerwinski,Australia Western Australia Western Australia
3,43293,Bougrier 2012 Rosé d'Anjou (Rosé) by Roger Voss,France,Loire Valley,84,13.0,"Typical, light and sweet rosé, fruity with bri...","Typical, light and sweet rosé, fruity with bri...",Rosé,Roger Voss,France Loire Valley Rosé d'Anjou
4,118523,Bolla 2007 Le Poiane (Valpolicella Classico S...,Italy,Veneto,87,14.0,If you aren't familiar with Ripasso (a hybrid ...,If you aren't familiar with Ripasso (a hybrid ...,"Corvina, Rondinella, Molinara",NaN,Italy Veneto Valpolicella Classico Superiore R...

In [110]:
corpus.sample(5)

,doc_key,doc_title,doc_label,doc_province,doc_points,doc_price,doc_content,doc_original,doc_variety,doc_taster,doc_place
doc_id,,,,,,,,,,,
1985,94180,Carmel Road 2012 Liberated Riesling (Arroyo Se...,US,California,85,16.0,This Riesling is distinctly off-dry. It's rich...,This Riesling is distinctly off-dry. It's rich...,Riesling,NaN,US California Arroyo Seco Central Coast
4790,22401,Barnard Griffin 2012 Syrah (Columbia Valley (W...,US,Washington,87,17.0,"Streaks of citrus, berry and cracker are integ...","Streaks of citrus, berry and cracker are integ...",Syrah,Paul Gregutt,US Washington Columbia Valley (WA) Columbia Va...
3174,75139,Cutruzzola 2011 Riven Rock Vineyard Riesling (...,US,California,87,22.0,"This polished, un-oaked Riesling shows the var...","This polished, un-oaked Riesling shows the var...",Riesling,NaN,US California San Luis Obispo County Central C...
225,39815,Leyendas de Familia 2009 Magia Negra Ensamblaj...,Chile,Maule Valley,90,69.0,"Herbal, olive-infused aromas of berry fruits a...","Herbal, olive-infused aromas of berry fruits a...",Bordeaux-style Red Blend,Michael Schachner,Chile Maule Valley
5883,74073,Lamiable NV Grand Cru Brut (Champagne) Grand ...,France,Champagne,91,NaN,Lamiable is a small house in Tours-sur-Marne a...,Lamiable is a small house in Tours-sur-Marne a...,Champagne Blend,Roger Voss,France Champagne Champagne

In [111]:
corpus.shape

(10000, 11)

In [112]:
corpus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   doc_key       10000 non-null  int64
 1   doc_title     10000 non-null  object
 2   doc_label     9993 non-null   object
 3   doc_province  9993 non-null   object
 4   doc_points    10000 non-null  int64
 5   doc_price     9301 non-null   float64
 6   doc_content   10000 non-null  object
 7   doc_original  10000 non-null  object
 8   doc_variety   10000 non-null  object
 9   doc_taster    7945 non-null   object
 10  doc_place     10000 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 859.5+ KB

# Create Bag-of-Words 

ie. a __Count Vector Space__

We use Scikit Learn's CountVectorizer to convert our F1 corpus of paragraphs into a document-term vector space of word counts.

In [113]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [114]:
count_engine = CountVectorizer(max_features=n_terms, stop_words='english', ngram_range=ngram_range)
count_model = count_engine.fit_transform(corpus.doc_content)

## Get Generated VOCAB

In [115]:
VOCAB = pd.DataFrame(count_engine.get_feature_names(), columns=['term_str'])
VOCAB = VOCAB.set_index('term_str')
# VOCAB.index.name = 'term_id' # For convenience, we'll use strings for IDs

## Get Generated Bag-of-Words

We do this just to show what the counter vectorizer produced. `DTM` stands for documet-term matrix. We convert this sparse matrix into a "thin" dataframe that keeps only terms with counts for each document.

In [116]:
DTM = pd.DataFrame(count_model.toarray(), index=corpus.index, columns=VOCAB.index)
BOW = DTM.stack().to_frame('n')
BOW = BOW[~(BOW.n == 0)]

In [117]:
DTM.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 4000 entries, 000 to zippy acidity
dtypes: int64(4000)
memory usage: 305.2 MB

In [118]:
BOW.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 267755 entries, (0, 'accented') to (9999, 'wine')
Columns: 1 entries, n to n
dtypes: int64(1)
memory usage: 3.2+ MB

## Compute TF-IDF

In [119]:
tfidf_engine = TfidfTransformer()
tfidf_model = tfidf_engine.fit_transform(count_model)

In [120]:
TFIDF = pd.DataFrame(tfidf_model.toarray(), index=corpus.index, columns=VOCAB.index)

In [121]:
BOW['tfidf'] = TFIDF.stack()

In [122]:
BOW

                    n     tfidf
doc_id term_str
0      accented     1  0.212521
       astringent   1  0.219259
       barrel       1  0.183510
       bit          1  0.164003
       bottle       1  0.198999
...                ..       ...
9999   showing      1  0.160109
       stone        1  0.161591
       stone fruit  1  0.177589
       texture      1  0.118262
       wine         1  0.059593

[267755 rows x 2 columns]

## Add Features to VOCAB

In [123]:
VOCAB['ngram_len'] = None # Since VOCAB has no columns yet
VOCAB['ngram_len'] = VOCAB.apply(lambda x: len(x.name.split()), 1)
VOCAB['n'] = DTM.sum()
VOCAB['tfidf_mean'] = TFIDF.mean()

In [124]:
VOCAB.ngram_len.value_counts()

1    2099
2    1722
3     172
4       7
Name: ngram_len, dtype: int64

In [125]:
# VOCAB[VOCAB.ngram_len == VOCAB.ngram_len.max()].sort_values('n', ascending=False)

In [126]:
# VOCAB.sort_values('n', ascending=False)

In [127]:
# VOCAB[VOCAB.ngram_len > 1].sort_values('n', ascending=False)

In [128]:
# VOCAB[VOCAB.ngram_len > 1].sort_values('tfidf_mean', ascending=False)

# Generate Topic Models

We run Scikit Learn's [LatentDirichletAllocation algorithm](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html#sklearn.decomposition.LatentDirichletAllocation) and extract the THETA and PHI tables.

In [129]:
from sklearn.decomposition import NMF, LatentDirichletAllocation as LDA

## Using LDA

In [130]:
lda = LDA(n_components=n_topics, max_iter=max_iter, learning_offset=50., random_state=0)

### THETA

In [131]:
if use_tfidf:
    THETA = pd.DataFrame(lda.fit_transform(tfidf_model), index=corpus.index)
else:
    THETA = pd.DataFrame(lda.fit_transform(count_model), index=corpus.index)
THETA.index.name = 'doc_id'
THETA.columns.name = 'topic_id'

In [132]:
THETA.sample(20).style.background_gradient()

In [133]:
# THETA.sum(1).sum()

### PHI

In [134]:
PHI = pd.DataFrame(lda.components_, columns=VOCAB.index)
PHI.index.name = 'topic_id'
PHI.columns.name  = 'term_str'

In [135]:
PHI.T.head().style.background_gradient()

### Create Topic Glosses

In [136]:
n_top_words = 7

In [137]:
TOPICS = PHI.stack().to_frame().rename(columns={0:'weight'})\
    .groupby('topic_id')\
    .apply(lambda x: 
           x.weight.sort_values(ascending=False)\
               .head(n_top_words)\
               .reset_index()\
               .drop('topic_id',1)\
               .term_str)

In [138]:
TOPICS

term_str,0,1,2,3,4,5,6
topic_id,,,,,,,
0,cherry,fruit,wine,aromas,flavors,bright,notes
1,cool climate,climate,italy,cool,lip,smacking,informal
2,flavors,wine,dr,fruit,dr pepper,lacking,blueberry
3,wine,tannins,drink,fruits,acidity,ripe,rich
4,white,palate,peach,apple,citrus,acidity,flavors
5,wine,acidity,drink,crisp,character,ripe,texture
6,pinot,cherry,pinot noir,noir,raspberry,red,flavors
7,wine fine,barrel,cherry crushed,fruit,time,crushed raspberry,red
8,black,wine,fruit,vineyard,cherry,tannins,flavors
9,finish,aromas,flavors,palate,fruit,green,nose
10,wine,flavors,black,fruit,long term,term,olive
11,berry,plum,flavors,finish,aromas,herbal,blackberry
12,acidity citrus,60,low acidity,lemon curd,curd,low,blend 60
13,cabernet,fruit,flavors,cherry,blend,wine,syrah
14,medium,bodied,flavors,medium bodied,cherries,bodied wine,wine
15,apple,lime,lemon,palate,pear,fresh,nose
16,flavors,wine,orange,nutty,sweet,fruit,acidity
17,palate,black,tannins,aromas,cherry,alongside,dried
18,wine,ripe,tannins,flavors,black,fruit,currants
19,flavors,oak,finish,fruit,wine,aromas,vanilla

In [139]:
TOPICS['topwords'] = TOPICS.apply(lambda x: str(x.name) + ' ' + ', '.join(x), 1)

### Add Doc Weights

In [140]:
TOPICS['doc_weight_sum'] = THETA.sum()

## Using NMF

In [141]:
nmf_engine = NMF(n_components=n_topics, init='nndsvd', random_state=1, alpha=.1, l1_ratio=.5)

### THETA

In [142]:
THETA_NMF = pd.DataFrame(nmf_engine.fit_transform(tfidf_model), index=corpus.index)
THETA_NMF.columns.name = 'topic_id'

In [143]:
THETA_NMF.sample(20).style.background_gradient()

### PHI

In [144]:
PHI_NMF = pd.DataFrame(nmf_engine.components_, columns=VOCAB.index)

In [145]:
PHI_NMF.index.name = 'topic_id'
PHI_NMF.columns.name  = 'term_str'

In [146]:
PHI_NMF.T.head().style.background_gradient()

### Topics

In [147]:
TOPICS_NMF = PHI_NMF.stack().to_frame().rename(columns={0:'weight'})\
    .groupby('topic_id')\
    .apply(lambda x: 
           x.weight.sort_values(ascending=False)\
               .head(n_top_words)\
               .reset_index()\
               .drop('topic_id',1)\
               .term_str)

In [148]:
TOPICS_NMF

term_str,0,1,2,3,4,5,6
topic_id,,,,,,,
0,wine,fruits,ripe,rich,drink,tannins,wood
1,crisp,light,acidity,fresh,bright,wine,fruity
2,lemon,lime,lemon lime,grapefruit,zest,riesling,orange
3,tannins,alongside,palate,aromas,cherry,offers,palate offers
4,cabernet,sauvignon,cabernet sauvignon,blend,merlot,franc,cabernet franc
5,red,red berry,red cherry,red fruit,red fruits,berry,red currant
6,berry,finish,plum,flavors,aromas,herbal,feels
7,black,black cherry,cherry,pepper,black pepper,blackberry,currant
8,fruit,fruit flavors,flavors,tropical fruit,black fruit,tropical,aromas
9,sweet,flavors,vanilla,like,pineapple,honey,soft
10,bodied,medium,medium bodied,bodied wine,medium bodied wine,texture,wine
11,nose,palate,notes,nose palate,finish,shows,bottling
12,oak,new,french,french oak,aged,new french,new french oak
13,pinot,noir,pinot noir,cherry,silky,raspberry,cola
14,dry,bone,bone dry,dry wine,dry tannins,wine dry,flavors
15,white,peach,white peach,stone,flower,citrus,stone fruit
16,cherries,blackberries,currants,years,raspberries,cola,blackberries cherries
17,apple,green,pear,green apple,apple pear,apple flavors,flavors
18,ready,ready drink,drink,wine ready,wine ready drink,soft,fruity
19,spice,spice flavors,baking spice,baking,cherry,flavors,vanilla

In [149]:
TOPICS_NMF['topwords'] = TOPICS_NMF.apply(lambda x: str(x.name) + ' ' + ', '.join(x), 1)

### Add Doc Weights

In [150]:
TOPICS_NMF['doc_weight_sum'] = THETA_NMF.sum()

In [151]:
TOPICS_NMF.iloc[:, 7:]

term_str                                           topwords  doc_weight_sum
topic_id
0          0 wine, fruits, ripe, rich, drink, tannins, wood       89.181919
1         1 crisp, light, acidity, fresh, bright, wine, ...       65.148885
2         2 lemon, lime, lemon lime, grapefruit, zest, r...       39.623773
3         3 tannins, alongside, palate, aromas, cherry, ...       67.308991
4         4 cabernet, sauvignon, cabernet sauvignon, ble...       44.589535
5         5 red, red berry, red cherry, red fruit, red f...       40.488300
6         6 berry, finish, plum, flavors, aromas, herbal...       70.376952
7         7 black, black cherry, cherry, pepper, black p...       57.334993
8         8 fruit, fruit flavors, flavors, tropical frui...       55.332295
9         9 sweet, flavors, vanilla, like, pineapple, ho...       60.523884
10        10 bodied, medium, medium bodied, bodied wine,...       34.803377
11        11 nose, palate, notes, nose palate, finish, s...       64.259420
12        12 oak, new, french, french oak, aged, new fre...       38.939023
13        13 pinot, noir, pinot noir, cherry, silky, ras...       32.281886
14        14 dry, bone, bone dry, dry wine, dry tannins,...       35.721871
15        15 white, peach, white peach, stone, flower, c...       49.729342
16        16 cherries, blackberries, currants, years, ra...       38.375325
17        17 apple, green, pear, green apple, apple pear...       42.457053
18        18 ready, ready drink, drink, wine ready, wine...       31.821509
19        19 spice, spice flavors, baking spice, baking,...       36.340132

# Save the Model

## Keep Corpus Label Info

This is effectively the LIB table.

In [152]:
LABELS = corpus[set(corpus.columns.tolist()) - set(['doc_key', 'doc_content', 'doc_original'])]

## Save each dataframe

This could of course be generalized as a function or class method.

In [153]:
LABELS.to_csv(f"{db_dir}/{data_prefix}-LABELS.csv", index=True)
VOCAB.to_csv(f"{db_dir}/{data_prefix}-VOCAB.csv", index=True)
BOW.to_csv(f"{db_dir}/{data_prefix}-BOW.csv", index=True)
TOPICS.to_csv(f"{db_dir}/{data_prefix}-TOPICS.csv", index=True)
THETA.to_csv(f"{db_dir}/{data_prefix}-THETA.csv", index=True)
PHI.to_csv(f"{db_dir}/{data_prefix}-PHI.csv", index=True)
TOPICS_NMF.to_csv(f"{db_dir}/{data_prefix}-TOPICS_NMF.csv", index=True)
THETA_NMF.to_csv(f"{db_dir}/{data_prefix}-THETA_NMF.csv", index=True)
PHI_NMF.to_csv(f"{db_dir}/{data_prefix}-PHI_NMF.csv", index=True)